Update readme for environment preparation.
- we need to add this to avoid the following error
```
python example.py --model cartesia-ai/Rene-v0.1-1.3b-4bit-mlx --prompt "Rene Descartes was"
Traceback (most recent call last):
  File "cartesia-ai/edge/cartesia-mlx/example.py", line 5, in <module>
    import cartesia_mlx as cmx
  File "cartesia-ai/edge/cartesia-mlx/cartesia_mlx/__init__.py", line 1, in <module>
    from cartesia_mlx.models.lm import LM
  File "cartesia-ai/edge/cartesia-mlx/cartesia_mlx/models/__init__.py", line 1, in <module>
    from cartesia_mlx.models.lm import LM
  File "cartesia-ai/edge/cartesia-mlx/cartesia_mlx/models/lm.py", line 15, in <module>
    from cartesia_mlx.utils.tokenizer import Tokenizer
  File "cartesia-ai/edge/cartesia-mlx/cartesia_mlx/utils/tokenizer.py", line 3, in <module>
    from transformers import AutoTokenizer
ModuleNotFoundError: No module named 'transformers'
```